//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSystem.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BankSystem.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ao.account_owner_id, ao.first_name, ao.last_name, cc.currency_code, SUM(ba.balance) AS Total
        ///FROM 
        ///     bank_account AS ba
        ///         LEFT JOIN 
        ///     account_owner AS ao
        ///             ON ao.account_owner_id=ba.account_owner_id
        ///         LEFT JOIN 
        ///     currency_code AS cc
        ///             ON ba.currency_code_id=cc.currency_code_id
        ///GROUP BY ao.account_owner_id, ao.first_name, ao.last_name, cc.currency_code
        ///ORDER BY Total DESC;.
        /// </summary>
        internal static string GetAcountOwnerTotalBalance {
            get {
                return ResourceManager.GetString("GetAcountOwnerTotalBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT bank_account_id, first_name, last_name, account_number, balance, currency_code, bonus_points, overdraft FROM 
        ///     account_owner AS ao 
        ///         LEFT JOIN 
        ///     bank_account AS ba 
        ///             ON ao.account_owner_id=ba.account_owner_id
        ///         LEFT JOIN 
        ///     currency_code AS cc
        ///             ON ba.currency_code_id=cc.currency_code_id;.
        /// </summary>
        internal static string GetBankAccountsInfo {
            get {
                return ResourceManager.GetString("GetBankAccountsInfo", resourceCulture);
            }
        }
    }
}
